server:
  port: 8080
spring:
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  config:
    name: schedule
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: schedule
        jdbc:
          time_zone: UTC
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
